Fix bug that causes node-fetch to error
TypeError: Cannot set property size of #<Object> which has only a getter
    at Request.Body (/Users/harmmartinkooistra/Documents/map-van-mark/JavaScript/npm projects/TestingWrapper/node_modules/node-fetch/lib/ind
ex.js:179:12)
    at new Request (/Users/harmmartinkooistra/Documents/map-van-mark/JavaScript/npm projects/TestingWrapper/node_modules/node-fetch/lib/index.js:1169:8)
    at /Users/harmmartinkooistra/Documents/map-van-mark/JavaScript/npm projects/TestingWrapper/node_modules/node-fetch/lib/index.js:1321:19
    at new Promise (<anonymous>)
    at fetch (/Users/harmmartinkooistra/Documents/map-van-mark/JavaScript/npm projects/TestingWrapper/node_modules/node-fetch/lib/index.js:1
319:9)